FROM ubuntu
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y
RUN apt-get install -y apt-utils
RUN apt-get -y install python3-pip
RUN pip3 install --upgrade robotframework-seleniumlibrary
RUN apt-get -y install firefox
RUN apt-get -y install wget
RUN wget -q https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz ;
RUN tar -C /usr/bin/ -xf geckodriver-*.tar.gz
